# Generated by Django 5.2.8 on 2025-11-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Movie name', max_length=100)),
                ('date', models.DateField(help_text='Enter a Movie date')),
            ],
        ),
    ]
